name: Update Cal HR Status

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # runs every 15 minutes

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: python cal_hr_tracker.py

      - name: Commit files
        run: |
          git config --global user.name "cal-dinger-bot"
          git config --global user.email "cal-dinger-bot@example.com"
          git add status.json
          git diff --cached --quiet && echo "No changes to commit" || \
          GIT_COMMITTER_NAME="cal-dinger-bot" GIT_COMMITTER_EMAIL="cal-dinger-bot@example.com" \
          git commit --author="cal-dinger-bot <cal-dinger-bot@example.com>" -m "Auto-update status.json [skip ci]"

      - name: Push changes using token
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: main
