name: Update Cal HR Status

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run the Cal HR script
        run: python cal_hr_tracker.py

      - name: Commit and push updated status.json
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git config --global user.name "cal-dinger-bot"
          git config --global user.email "cal-dinger-bot@example.com"

          # DEBUG: Show the current Git remote URL
          echo "Git remote BEFORE:" 
          git remote -v

          # Set remote using PAT
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${REPO}

          echo "Git remote AFTER:"
          git remote -v

          git fetch origin main
          git checkout main
          git pull origin main

          git add status.json
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto-update status.json [skip ci]"

          # DEBUG: Show what's staged
          git status

          git push origin main
