name: Debug PAT and Git

on:
  workflow_dispatch:

jobs:
  debug-pat-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print GitHub context
        run: echo "Repo: ${{ github.repository }}"

      - name: Set and print Git remote with PAT
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git config --global user.name "cal-dinger-bot"
          git config --global user.email "cal-dinger-bot@example.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${REPO}
          git remote -v
          echo "PAT Token present? -> ${GH_TOKEN:+yes}"
